### ISSUE TITLE
Add support for @grab/@quote

### ISSUE THREAD

**Issue by earldouglas** [earldouglas/sectery#175]
See *Substitute.scala* for the general pattern of tracking each user's most recent message in the `LAST_MESSAGE` table.  We might want to just re-use that table for this, perhaps factoring the code for it out into something like *LastMessage.scala*.

**Comment by FreddieSanchez** [comment]
We could save all messages, and then @grab will not be needed. @quote could be used to get a random one. _Substitute.scala_ could then just act on the last message from each user. 

e,g. Assuming a `messages` table.

```
// returns the last message from each user
SELECT `message` FROM `messages`
WHERE
`CHANNEL` = <channel>
GROUP BY
  `NICK`
ORDER BY 
  `MILLIS` DESC
```
